services:
  postgres_ocorrencias:
    build: .
    container_name: postgres_ocorrencias
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  valhalla:
    image: ghcr.io/valhalla/valhalla-scripted:latest
    container_name: criminalidade-valhalla
    restart: unless-stopped
    ports:
      - "8002:8002"
    volumes:
      - ./custom_files:/custom_files
    environment:
      - tile_urls=http://download.geofabrik.de/south-america/brazil/sudeste-latest.osm.pbf
      - server_threads=4
      - use_tiles_ignore_pbf=False
      - build_elevation=False
      - build_admins=True
      - build_time_zones=True
      - build_transit=False

volumes:
  postgres_data:
