"""restore route requests

Revision ID: 53efdb0a86b1
Revises: f55e3423574a
Create Date: 2026-10-09 19:31:52.381090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53efdb0a86b1'
down_revision: Union[str, Sequence[str], None] = 'f55e3423574a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('route_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('origin', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('destination', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('transport_mode', postgresql.ENUM('auto', 'bicycle', 'bus', 'truck', 'taxi', 'motor_scooter', 'motorcycle', 'pedestrian', 'bikeshare', 'multimodal', name='transport_mode'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_route_requests_destination', 'route_requests', ['destination'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index('idx_route_requests_origin', 'route_requests', ['origin'], unique=False, postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index('idx_route_requests_origin', table_name='route_requests', postgresql_using='gist', column_name='origin')
    op.drop_geospatial_index('idx_route_requests_destination', table_name='route_requests', postgresql_using='gist', column_name='destination')
    op.drop_geospatial_table('route_requests')
    # ### end Alembic commands ###
