"""descricao da alteracao

Revision ID: f55e3423574a
Revises: f21c622f3f1d
Create Date: 2026-10-09 19:00:42.102257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f55e3423574a'
down_revision: Union[str, Sequence[str], None] = 'f21c622f3f1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index(op.f('idx_route_requests_destination'), table_name='route_requests', postgresql_using='gist', column_name='destination')
    op.drop_geospatial_index(op.f('idx_route_requests_origin'), table_name='route_requests', postgresql_using='gist', column_name='origin')
    op.drop_geospatial_table('route_requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('route_requests',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('origin', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True), autoincrement=False, nullable=False),
    sa.Column('destination', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, _spatial_index_reflected=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('route_requests_pkey'))
    )
    op.create_geospatial_index(op.f('idx_route_requests_origin'), 'route_requests', ['origin'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_geospatial_index(op.f('idx_route_requests_destination'), 'route_requests', ['destination'], unique=False, postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###
